version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/node:24.18.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist

  publish:
    resource_class: small
    docker:
      - image: cimg/node:22.14.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Bump version and commit changes
          command: |
            # TODO: Automate versioning
            npm version patch -m "chore(release): bump version to %s"
            git push --follow-tags
      - run:
          name: Publish to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
            npm publish --access=public
      - run:
          name: Publish to GitHub Packages
          command: |
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_TOKEN}" > .npmrc
            npm publish --registry=https://npm.pkg.github.com

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: develop
